on: push
name: deploy
jobs:
  deploy:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push laravel app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            CICD_GIT_COMMIT=${GITHUB_SHA:7}
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/ghostzero/k8s:latest
      - name: deploy to cluster
        uses: ghostzero/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f okteto.yml
      - name: verify deployment
        uses: ghostzero/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout status deployment/hello-world-deployment"
